// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgyjzzzzqackgygujzfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndneWp6enp6cWFja2d5Z3VqemZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODU4NzIsImV4cCI6MjA3MjQ2MTg3Mn0.PSgRng5n1Yj-P5tQmTB78vAfbcF6YdzHAG7XcmDzdN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});